### ISSUE TITLE
No (formal) license 

### ISSUE THREAD

**Issue by Eeems** [sowcow/blank_slate_pdf#1]
With no license, it's not clear what the user is and isn't allowed to do with the code here.

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

**Comment by sowcow** [comment]
C'mon this is the least formal license to exist. Having a special file or more than one line in README is informally forbidden.

**Comment by Eeems** [comment]
> C'mon this is the least formal license to exist. Having a special file or more than one line for it in README is not permitted by the spirit of it.

Not according to the WTFPL FAQs http://www.wtfpl.net/faq/

**Comment by sowcow** [comment]
F*rk it.

**Comment by Eeems** [comment]
I'm not sure why you are entertaining a conversation with me instead of closing the issue, if your answer is that you are already fine with how it is.

**Comment by sowcow** [comment]
Maybe I'll fork WTFPL first into something more usable. No idea yet.
